### ISSUE TITLE
[BUG] OS platform error when using the tool in Github composite actions

### ISSUE THREAD

**Issue by neatcoder** [vcsjones/AzureSignTool#173]
Github Composite action:
```yaml
name: Github composite action
runs:
  using: "composite"
  steps:
    - run: |
        dotnet tool install --global AzureSignTool --version 3.0.0
        azuresigntool --help
      shell: pwsh
```
Log:
```
You can invoke the tool using the following command: azuresigntool
Tool 'azuresigntool' (version '3.0.0') was successfully installed.

Azure Sign Tool is only supported on Windows.
```
