### ISSUE TITLE
Unable to find certificate -- not sure where I'm going wrong

### ISSUE THREAD

**Issue by SeanKilleen** [vcsjones/AzureSignTool#84]
Hi! Firstly, thank you for this tool. Secondly, this is a low priority issue, and I'm 98% sure it's my fault, so if you happen to be able to point me in the right direction, I'd appreciate it.

## Background / Goal

I recently bit the bullet got an Authenticode cert to sign an office add-in I want to publish. 

Goals: 

* Use AzureSignTool within an AzureDevOps pipeline to sign the `setup.exe` file produced by my build process. 
* Double-check that this is "enough" in this case.

## What I've Done

* Obtained the cert
* Uploaded the cert into an Azure KeyVault I created
* Registered an app in my Azure AD
* Granted the app access to the Azure KeyVault
* Used the app ID as my client ID and a generated client secret as my secret.
* Installed AzureSignTool as a global tool within my pipeline steps:

```yml
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global azuresigntool'
  displayName: Install AzureSignTool
```

* Called the AzureSignTool from the command line (info redacted);

```yml
- task: CmdLine@2
  displayName: 'Sign outputted .exe with AzureSignTool'
  inputs:
    script: "AzureSignTool.exe sign -du 'https://killeencode.com' -kvu 'https://[REDACTED].vault.azure.net' -kvi '[REDACTED]' -kvs '[REDACTED]' -kvc '[REDACTED]' -v setup.exe"
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
```

## The Problem

No matter what, AzureSignTool appears unable to find the cert:

```log
trce: AzureSignTool.Program[0]
      Retrieving certificate '[REDACTED]'.
fail: AzureSignTool.Program[0]
      Failed to retrieve certificate '[REDACTED]' from Azure Key Vault. Please verify the name of the certificate and the permissions to the certificate.
info: AzureSignTool.Program[0]
      Failed to get configuration from Azure Key Vault.
##[error]Cmd.exe exited with code '-2147024809'.
```

## What I've confirmed (or so I think)

* The KeyVault URL is correct -- copied it directly from portal
* The application ID from my Azure AD app registration is being used as the input to `-kvi`
* The client secret for my application in AD is being used as the input to `-kvs`
* The cert name is correct (copied from keyvault in portal)
* The application's service principal has permissions on the key vault (Owner for now)
* In the KeyVault's access policy, the application's service principal has every single permission (for now, to remove this as a variable)

## Things I think it could be

The DevOps pipeline is under a different account than the azure subscription, and thus a different directory. I am wondering if the DevOps pipeline isn't able to access the keyvault across subscriptions? Although with the client ID and secret, I thought that'd be mitigated.

Any insight into what it could be would be greatly appreciated; I'm somewhat new to this and I've exhausted the other resources I'm aware of. Hoping someone with more experience here can spot it quickly,

**Comment by vcsjones** [comment]
Hiya - just to make sure we are using the right things from the Azure Portal... let me show some screenshots of how I have it working.

1. Grab the key vault URL. Based on your YAML, it seems correct, but here's mine:

    ![1](https://user-images.githubusercontent.com/361677/82127663-5f15de00-9783-11ea-8333-61f86ee9dec6.png)

    This maps to the `-kvu` parameter.

2. Create an App Registration. The `Application (client) ID` is the `-kvi` parameter. It should be a GUID.

    ![3](https://user-images.githubusercontent.com/361677/82127697-9c7a6b80-9783-11ea-89c8-b0c1eb42af6f.png)

3. Next, create a secret for it. 

    ![2](https://user-images.githubusercontent.com/361677/82127716-c2077500-9783-11ea-8802-32d34e555176.png)

    It's the tqonpblahblahblah value. This maps to `-kvs`. 

4. Last is the name of the Certificate. It comes from here:
    
    ![4](https://user-images.githubusercontent.com/361677/82127743-ecf1c900-9783-11ea-94e4-5559130c9120.

**Comment by vcsjones** [comment]
My keyboard flipped out and it hit post early 🤷‍♀️ on my previous post.

Anyway, that is a complete example of the parts needed, sorry if all of that was obvious to you but I could have done a better job documenting where all these values come from.

Regarding your hunch, you might be right - I'll be frank and say that Azure Identity confuses the hell of out me. Are you able to get it working from your desktop for example?

**Comment by vcsjones** [comment]
(For what it's worth I already tore down the example values from the screenshots, but if you want to test it with one of my self-signed testing certificates we can work offline to get a set of credentials, so that way you should have a known-working set of values to see if it is environment related or not).

**Comment by vcsjones** [comment]
Oh, regarding permissions, your app needs permission to a few things.

1. Verify, Sign, Get, List on Key Permissions
2. Get, List on Secret Permissions
3. Get, List on Certificate Permissions

in here

![image](https://user-images.githubusercontent.com/361677/82127954-355db680-9785-11ea-9fdf-9ff7c257f5f4.png)

**Comment by SeanKilleen** [comment]
Thanks for a quick response! It's good to know I'm not crazy at least based on what you've sent so far. 

I believe I am indeed pulling the values from the same places you are, but I will be sure to confirm that specifically. No need to be sorry -- I am brand spanking new to this sort of signing process so it's really helpful. I may to a PR after this with some light docs and some of these screenshots to help others going forward.

Good call on trying from my desktop. That should give me a way to switch accounts and verify whether that's the variable. I'll do that when I get a chance, hopefully today.

Also I appreciate the permissions note. Right now it has everything, but I'll of course trim it down and that guidance is great.

I'll also try with my self-signed cert to rule out other weirdness.

You've given me a lot of good next steps quickly. Thanks again! I'll keep this issue updated as I progress.

**Comment by SeanKilleen** [comment]
Surely enough, as you suggested, I ran the same exact call locally on a DLL file rather than a `setup.exe` and it retrieved the cert and signed it correctly.

I think this actually might be something I dig into on the Azure DevOps side as a possible bug. I'll try recreating this pipeline under the account that has access to this subscription to see if that confirms the workaround. 

Regardless, your quick walkthrough was helpful! I'll turn it into a doc PR before closing this issue.

**Comment by SeanKilleen** [comment]
Also FYI, I created #85 to add some more verbose logging when this happens. I might compile locally and with the contents of that PR and see if I can use the exe as part of my exploration of the issue.

**Comment by SeanKilleen** [comment]
This may have turned out to be nothing more than me terribly formatting the input in AzureDevOps.

I compiled my own copy of AzureSignTool based on #85, began to play around with it, couldn't get to the spot where I saw my logging output. Adjusted the input and then....it worked. And then I tried with the global tool and....it worked. 🤦‍♂️ 

The input that worked, in case anyone else is having this issue:

```yml
- task: CmdLine@2
  displayName: 'Sign outputted .exe with global AzureSignTool'
  inputs:
    script: AzureSignTool sign -du "https://killeencode.com" -kvu "https://[VAULT_ID].vault.azure.net" -kvi "[REDACTED_APPLICATION_ID]" -kvs "[REDACTED_APPLICATION_CLIENT_SECRET" -kvc "[REDACTED_CERT_NAME]" -v $(Build.ArtifactStagingDirectory)\\setup.exe
```
I'll capture the steps here in a PR and then close this issue.
